services:
  app:
    environment:
      - LISTEN_PORT
      - MONGODB_URL
      - MONGODB_USERAUTHMODEL
      - TOKEN_SECRET
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"
    ports:
      - "${DOCKER_FORWARD_PORT}:${DOCKER_LISTEN_PORT}"
    restart: "unless-stopped"
  mongodb:
    image: "mongo:latest"
    restart: "unless-stopped"

networks:
  default:
    name: "${DOCKER_NETWORK}"
    external: true
