services:
  webhook:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "waxarsatia/userauth-backend:latest"
    ports:
      - "4001:80"
    restart: unless-stopped

networks:
  default:
    name: "gacha"
    external: true
