services:
  app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"
    ports:
      - "${DOCKER_FORWARD_PORT}:${DOCKER_LISTEN_PORT}"
    restart: "unless-stopped"
  mongodb:
    image: "mongo:latest"

networks:
  default:
    name: "${DOCKER_NETWORK}"
    external: true
