services:
  app:
    environment:
      - JWT_SECRET
      - JWT_SECRET_REFRESH
      - LISTEN_PORT
      - MONGODB_URL
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USER
      - MAIL_PASS
      - DKIM_DOMAIN
      - DKIM_KEYSELECTOR
      - DKIM_PRIVKEY
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"
    ports:
      - "${DOCKER_FORWARD_PORT}:${DOCKER_LISTEN_PORT}"
    restart: "unless-stopped"
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    image: "mongo:latest"
    restart: "unless-stopped"
    volumes:
      - "/data/db"

networks:
  default:
    name: "${DOCKER_NETWORK}"
    external: true
